spring:
  application.name: chordax_pdf_creation

########################### CONFIG ############################################
  config.import: optional:configserver:http://localhost:8888
  cloud.config.uri: http://localhost:8888

########################### EUREKA - SERVICE DISCOVERY #######################
eureka:
  client.serviceUrl.defaultZone:
  instance.preferIpAddress:

########################### PORT ############################################
server.port: