spring.application.name: chordax_pdf_creation

########################### PORT ############################################
server.port: 8081

########################### EUREKA ############################################
eureka:
  client.serviceUrl.defaultZone: http://localhost:8765/eureka
  instance.preferIpAddress: true